
## Notes:
#
# 1. Cannot easily ignore changes in paths (see https://gitlab.com/gitlab-org/gitlab/-/issues/198688).default:
#    * Use case: don't run a pipeline if we're just changing a README.
# 2. xxxx
#

# List of stages for jobs, and their order of execution:
stages:
  - test
  - deploy

# Global variables:
variables:
  FILE_PATH: "Dockerfile"

# Ordered list of jobs

# Job to test whether the container image can be built from a feature branch's source.
test:
  stage: test

  script:
    - podman build --file ${FILE_PATH} --tag local-image:$CI_COMMIT_REF_SLUG .

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

# Job to build and deploy the tagged container image to the associated GitLab container registry.
deploy:
  stage: deploy
  resource_group: production

  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - podman build --pull --file ${FILE_PATH} --build-arg imageversion=$CI_COMMIT_TAG --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - podman push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"

  after_script:
    - podman logout

  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+.*/
