apiVersion: v1
kind: Pod
metadata:
  name: appionprotomo
  labels:
    app: appionprotomo
spec:
  containers:
    - name: appionprotomo
      image: 'gitlab.chpc.utah.edu:5050/chpc/projects/appion-protomo:2.0.2'
      imagePullPolicy: Never
      ports:
        - name: webport
          containerPort: 80
          hostPort: 8080
          protocol: TCP
        - name: vncport
          containerPort: 5901
          hostPort: 5901
          protocol: TCP
        - name: dbport
          containerPort: 3306
          hostPort: 3306
          protocol: TCP
      securityContext: {}
      tty: true
      volumeMounts:
        - mountPath: /emg/data
          name: emg-data
        - mountPath: /var/lib/mysql
          name: mariadb-pvc
        - mountPath: /local_data
          name: local-data
        - mountPath: /etc/httpd/conf/httpd.conf
          name: apache-conf
      workingDir: /sw/myami/appion
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
  hostname: appionprotomo
  restartPolicy: Never    # Let systemd handle this.
  volumes:
    - name: emg-data
      hostPath:
        path: /scratch/local/podman/emg/data
        type: Directory
    - name: local-data
      hostPath:
        path: /scratch/local/podman/appion-protomo
        type: Directory
    - name: apache-conf
      hostPath:
        path: /scratch/local/podman/appion-protomo/config/httpd.conf
        type: File
    - name: mariadb-pvc
      persistentVolumeClaim:
        claimName: mariadb-database
