
name: "Pull Request Checks (Image)"
concurrency:
  group: prc-image-${{ github.repository }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - '.gitignore'
      - 'LICENSE'
      - '**.md'

env:
  FILE_PATH: "Dockerfile"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "${{ env.FILE_PATH }}"
          load: true
          push: false
          tags: local-image:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
